---
date: "{{ lookup('pipe', 'date +%d-%h-%Y') }}" # -%T') }}"
filehost_details: 192.168.173.33
Activity_Name: Linux_Patching
dbname: aarmor
dbuser: aarmor
dbpassword: Welcome@2020$
package_list:
  - rest
  - wget
