---
- hosts: all #"{{survey_host}}"
  gather_facts: no
  become_user: root
  become: yes
  strategy: free
          
  tasks:
  - name: include Load-Inventory
    include_role: 
     name: Load-Inventory
