---
- hosts: all #"{{survey_host}}"
  gather_facts: no
  become_user: root
  become: yes
  strategy: free
          
  tasks:
  - name: include Clear-Disk-Usage
    include_role: 
     name: Clear-Disk-Usage
